
const 
MINIMUM_DISTANCE_BETWEEN_TOWNS = 5,
TOWN_SIGHT_RADIUS = 3,
hurryCostPerUnit = 5,
UNIT_SIGHT_RADIUS = 2,
UNHAPPINESS_ALLOWANCE = 4,
UNHAPPINESS_RATE = 2,
BASE_POPULATION_LIMIT = 8,
MAX_UNHAPPINESS_REDUCTION_FROM_UNITS = 3
;

export  {
    MINIMUM_DISTANCE_BETWEEN_TOWNS,
    TOWN_SIGHT_RADIUS,
    hurryCostPerUnit,
    UNIT_SIGHT_RADIUS,
    UNHAPPINESS_ALLOWANCE,
    UNHAPPINESS_RATE,
    BASE_POPULATION_LIMIT,
    MAX_UNHAPPINESS_REDUCTION_FROM_UNITS,
}